services:
  # 1. ฐานข้อมูล (Managed PostgreSQL)
  # Render จะดูแลเรื่อง Backup และความเสถียรให้
  - type: database
    name: my-postgres-db
    databaseName: django_db
    user: django_user
    plan: free

  # 2. ตัวเว็บ Django (รันจาก Dockerfile ของคุณ)
  - type: web
    name: django-web-app
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        value: asdasdakdadkja # แนะนำให้ใช้ generateValue: true แทน
      - key: ALLOWED_HOSTS
        value: .onrender.com # ยอมรับทุก sub-domain ของ render
    plan: free