databases:
  - name: my-postgres-db
    databaseName: django_db
    user: django_user
    plan: free

services:
  - type: web
    name: django-web-app
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        value: asdasdakdadkja # หรือใช้ generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_DEBUG_FALSE
        value: "1"